// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.13.0
// source: upstream.proto

package proto

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type OutputStreamRequest_Broadcast int32

const (
	OutputStreamRequest_BROADCAST_ALL        OutputStreamRequest_Broadcast = 0
	OutputStreamRequest_BROADCAST_ACTIVE     OutputStreamRequest_Broadcast = 1
	OutputStreamRequest_BROADCAST_NOT_ACTIVE OutputStreamRequest_Broadcast = 2
)

// Enum value maps for OutputStreamRequest_Broadcast.
var (
	OutputStreamRequest_Broadcast_name = map[int32]string{
		0: "BROADCAST_ALL",
		1: "BROADCAST_ACTIVE",
		2: "BROADCAST_NOT_ACTIVE",
	}
	OutputStreamRequest_Broadcast_value = map[string]int32{
		"BROADCAST_ALL":        0,
		"BROADCAST_ACTIVE":     1,
		"BROADCAST_NOT_ACTIVE": 2,
	}
)

func (x OutputStreamRequest_Broadcast) Enum() *OutputStreamRequest_Broadcast {
	p := new(OutputStreamRequest_Broadcast)
	*p = x
	return p
}

func (x OutputStreamRequest_Broadcast) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OutputStreamRequest_Broadcast) Descriptor() protoreflect.EnumDescriptor {
	return file_upstream_proto_enumTypes[0].Descriptor()
}

func (OutputStreamRequest_Broadcast) Type() protoreflect.EnumType {
	return &file_upstream_proto_enumTypes[0]
}

func (x OutputStreamRequest_Broadcast) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OutputStreamRequest_Broadcast.Descriptor instead.
func (OutputStreamRequest_Broadcast) EnumDescriptor() ([]byte, []int) {
	return file_upstream_proto_rawDescGZIP(), []int{3, 0}
}

type ReadyResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Time  string `protobuf:"bytes,1,opt,name=time,proto3" json:"time,omitempty"`
	Ready bool   `protobuf:"varint,2,opt,name=ready,proto3" json:"ready,omitempty"`
}

func (x *ReadyResult) Reset() {
	*x = ReadyResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_upstream_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadyResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadyResult) ProtoMessage() {}

func (x *ReadyResult) ProtoReflect() protoreflect.Message {
	mi := &file_upstream_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadyResult.ProtoReflect.Descriptor instead.
func (*ReadyResult) Descriptor() ([]byte, []int) {
	return file_upstream_proto_rawDescGZIP(), []int{0}
}

func (x *ReadyResult) GetTime() string {
	if x != nil {
		return x.Time
	}
	return ""
}

func (x *ReadyResult) GetReady() bool {
	if x != nil {
		return x.Ready
	}
	return false
}

type LiveResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Time string `protobuf:"bytes,1,opt,name=time,proto3" json:"time,omitempty"`
	Live bool   `protobuf:"varint,2,opt,name=live,proto3" json:"live,omitempty"`
}

func (x *LiveResult) Reset() {
	*x = LiveResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_upstream_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LiveResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LiveResult) ProtoMessage() {}

func (x *LiveResult) ProtoReflect() protoreflect.Message {
	mi := &file_upstream_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LiveResult.ProtoReflect.Descriptor instead.
func (*LiveResult) Descriptor() ([]byte, []int) {
	return file_upstream_proto_rawDescGZIP(), []int{1}
}

func (x *LiveResult) GetTime() string {
	if x != nil {
		return x.Time
	}
	return ""
}

func (x *LiveResult) GetLive() bool {
	if x != nil {
		return x.Live
	}
	return false
}

/// Request going from downstream (clients) to upstreams (servers)
type InputStreamRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Time       string `protobuf:"bytes,1,opt,name=time,proto3" json:"time,omitempty"`
	ClientUuid string `protobuf:"bytes,2,opt,name=client_uuid,json=clientUuid,proto3" json:"client_uuid,omitempty"`
	Payload    []byte `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
}

func (x *InputStreamRequest) Reset() {
	*x = InputStreamRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_upstream_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InputStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InputStreamRequest) ProtoMessage() {}

func (x *InputStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_upstream_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InputStreamRequest.ProtoReflect.Descriptor instead.
func (*InputStreamRequest) Descriptor() ([]byte, []int) {
	return file_upstream_proto_rawDescGZIP(), []int{2}
}

func (x *InputStreamRequest) GetTime() string {
	if x != nil {
		return x.Time
	}
	return ""
}

func (x *InputStreamRequest) GetClientUuid() string {
	if x != nil {
		return x.ClientUuid
	}
	return ""
}

func (x *InputStreamRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

/// Request going from upstream (servers) to downstreams (clients)
type OutputStreamRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Time string `protobuf:"bytes,1,opt,name=time,proto3" json:"time,omitempty"`
	// Types that are assignable to Target:
	//	*OutputStreamRequest_ClientUuid
	//	*OutputStreamRequest_Broadcast_
	Target  isOutputStreamRequest_Target `protobuf_oneof:"target"`
	Payload []byte                       `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`
}

func (x *OutputStreamRequest) Reset() {
	*x = OutputStreamRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_upstream_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OutputStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OutputStreamRequest) ProtoMessage() {}

func (x *OutputStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_upstream_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OutputStreamRequest.ProtoReflect.Descriptor instead.
func (*OutputStreamRequest) Descriptor() ([]byte, []int) {
	return file_upstream_proto_rawDescGZIP(), []int{3}
}

func (x *OutputStreamRequest) GetTime() string {
	if x != nil {
		return x.Time
	}
	return ""
}

func (m *OutputStreamRequest) GetTarget() isOutputStreamRequest_Target {
	if m != nil {
		return m.Target
	}
	return nil
}

func (x *OutputStreamRequest) GetClientUuid() string {
	if x, ok := x.GetTarget().(*OutputStreamRequest_ClientUuid); ok {
		return x.ClientUuid
	}
	return ""
}

func (x *OutputStreamRequest) GetBroadcast() OutputStreamRequest_Broadcast {
	if x, ok := x.GetTarget().(*OutputStreamRequest_Broadcast_); ok {
		return x.Broadcast
	}
	return OutputStreamRequest_BROADCAST_ALL
}

func (x *OutputStreamRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type isOutputStreamRequest_Target interface {
	isOutputStreamRequest_Target()
}

type OutputStreamRequest_ClientUuid struct {
	ClientUuid string `protobuf:"bytes,2,opt,name=client_uuid,json=clientUuid,proto3,oneof"`
}

type OutputStreamRequest_Broadcast_ struct {
	Broadcast OutputStreamRequest_Broadcast `protobuf:"varint,3,opt,name=broadcast,proto3,enum=upstream.grpc.service.OutputStreamRequest_Broadcast,oneof"`
}

func (*OutputStreamRequest_ClientUuid) isOutputStreamRequest_Target() {}

func (*OutputStreamRequest_Broadcast_) isOutputStreamRequest_Target() {}

var File_upstream_proto protoreflect.FileDescriptor

var file_upstream_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x75, 0x70, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x15, 0x75, 0x70, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x1a, 0x0b, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x37, 0x0a, 0x0b, 0x52, 0x65, 0x61, 0x64, 0x79, 0x52, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x72, 0x65, 0x61, 0x64, 0x79,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x72, 0x65, 0x61, 0x64, 0x79, 0x22, 0x34, 0x0a,
	0x0a, 0x4c, 0x69, 0x76, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x74,
	0x69, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x12,
	0x12, 0x0a, 0x04, 0x6c, 0x69, 0x76, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x04, 0x6c,
	0x69, 0x76, 0x65, 0x22, 0x63, 0x0a, 0x12, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x53, 0x74, 0x72, 0x65,
	0x61, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x69, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x12, 0x1f, 0x0a,
	0x0b, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x75, 0x75, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0a, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x55, 0x75, 0x69, 0x64, 0x12, 0x18,
	0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x22, 0x96, 0x02, 0x0a, 0x13, 0x4f, 0x75, 0x74,
	0x70, 0x75, 0x74, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x12, 0x0a, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x74, 0x69, 0x6d, 0x65, 0x12, 0x21, 0x0a, 0x0b, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x75,
	0x75, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x0a, 0x63, 0x6c, 0x69,
	0x65, 0x6e, 0x74, 0x55, 0x75, 0x69, 0x64, 0x12, 0x54, 0x0a, 0x09, 0x62, 0x72, 0x6f, 0x61, 0x64,
	0x63, 0x61, 0x73, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x34, 0x2e, 0x75, 0x70, 0x73,
	0x74, 0x72, 0x65, 0x61, 0x6d, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x2e, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x42, 0x72, 0x6f, 0x61, 0x64, 0x63, 0x61, 0x73, 0x74,
	0x48, 0x00, 0x52, 0x09, 0x62, 0x72, 0x6f, 0x61, 0x64, 0x63, 0x61, 0x73, 0x74, 0x12, 0x18, 0x0a,
	0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07,
	0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x22, 0x4e, 0x0a, 0x09, 0x42, 0x72, 0x6f, 0x61, 0x64,
	0x63, 0x61, 0x73, 0x74, 0x12, 0x11, 0x0a, 0x0d, 0x42, 0x52, 0x4f, 0x41, 0x44, 0x43, 0x41, 0x53,
	0x54, 0x5f, 0x41, 0x4c, 0x4c, 0x10, 0x00, 0x12, 0x14, 0x0a, 0x10, 0x42, 0x52, 0x4f, 0x41, 0x44,
	0x43, 0x41, 0x53, 0x54, 0x5f, 0x41, 0x43, 0x54, 0x49, 0x56, 0x45, 0x10, 0x01, 0x12, 0x18, 0x0a,
	0x14, 0x42, 0x52, 0x4f, 0x41, 0x44, 0x43, 0x41, 0x53, 0x54, 0x5f, 0x4e, 0x4f, 0x54, 0x5f, 0x41,
	0x43, 0x54, 0x49, 0x56, 0x45, 0x10, 0x02, 0x42, 0x08, 0x0a, 0x06, 0x74, 0x61, 0x72, 0x67, 0x65,
	0x74, 0x32, 0x98, 0x02, 0x0a, 0x13, 0x55, 0x70, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x50, 0x65,
	0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x75, 0x0a, 0x16, 0x62, 0x69, 0x64,
	0x69, 0x72, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d,
	0x69, 0x6e, 0x67, 0x12, 0x29, 0x2e, 0x75, 0x70, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x2e, 0x67,
	0x72, 0x70, 0x63, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x49, 0x6e, 0x70, 0x75,
	0x74, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2a,
	0x2e, 0x75, 0x70, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x53, 0x74, 0x72,
	0x65, 0x61, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x00, 0x28, 0x01, 0x30, 0x01,
	0x12, 0x43, 0x0a, 0x05, 0x72, 0x65, 0x61, 0x64, 0x79, 0x12, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74,
	0x79, 0x1a, 0x22, 0x2e, 0x75, 0x70, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x2e, 0x67, 0x72, 0x70,
	0x63, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x52, 0x65, 0x61, 0x64, 0x79, 0x52,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x45, 0x0a, 0x04, 0x6c, 0x69, 0x76, 0x65, 0x12, 0x16, 0x2e,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e,
	0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x21, 0x2e, 0x75, 0x70, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d,
	0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x4c, 0x69,
	0x76, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x28, 0x01, 0x30, 0x01, 0x42, 0x1d, 0x5a, 0x1b,
	0x70, 0x65, 0x72, 0x73, 0x69, 0x73, 0x74, 0x65, 0x6e, 0x74, 0x5f, 0x6d, 0x61, 0x72, 0x6b, 0x69,
	0x6e, 0x67, 0x5f, 0x6c, 0x62, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_upstream_proto_rawDescOnce sync.Once
	file_upstream_proto_rawDescData = file_upstream_proto_rawDesc
)

func file_upstream_proto_rawDescGZIP() []byte {
	file_upstream_proto_rawDescOnce.Do(func() {
		file_upstream_proto_rawDescData = protoimpl.X.CompressGZIP(file_upstream_proto_rawDescData)
	})
	return file_upstream_proto_rawDescData
}

var file_upstream_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_upstream_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_upstream_proto_goTypes = []interface{}{
	(OutputStreamRequest_Broadcast)(0), // 0: upstream.grpc.service.OutputStreamRequest.Broadcast
	(*ReadyResult)(nil),                // 1: upstream.grpc.service.ReadyResult
	(*LiveResult)(nil),                 // 2: upstream.grpc.service.LiveResult
	(*InputStreamRequest)(nil),         // 3: upstream.grpc.service.InputStreamRequest
	(*OutputStreamRequest)(nil),        // 4: upstream.grpc.service.OutputStreamRequest
	(*emptypb.Empty)(nil),              // 5: google.protobuf.Empty
}
var file_upstream_proto_depIdxs = []int32{
	0, // 0: upstream.grpc.service.OutputStreamRequest.broadcast:type_name -> upstream.grpc.service.OutputStreamRequest.Broadcast
	3, // 1: upstream.grpc.service.UpstreamPeerService.bidirectionalStreaming:input_type -> upstream.grpc.service.InputStreamRequest
	5, // 2: upstream.grpc.service.UpstreamPeerService.ready:input_type -> google.protobuf.Empty
	5, // 3: upstream.grpc.service.UpstreamPeerService.live:input_type -> google.protobuf.Empty
	4, // 4: upstream.grpc.service.UpstreamPeerService.bidirectionalStreaming:output_type -> upstream.grpc.service.OutputStreamRequest
	1, // 5: upstream.grpc.service.UpstreamPeerService.ready:output_type -> upstream.grpc.service.ReadyResult
	2, // 6: upstream.grpc.service.UpstreamPeerService.live:output_type -> upstream.grpc.service.LiveResult
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_upstream_proto_init() }
func file_upstream_proto_init() {
	if File_upstream_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_upstream_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadyResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_upstream_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LiveResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_upstream_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InputStreamRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_upstream_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OutputStreamRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_upstream_proto_msgTypes[3].OneofWrappers = []interface{}{
		(*OutputStreamRequest_ClientUuid)(nil),
		(*OutputStreamRequest_Broadcast_)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_upstream_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_upstream_proto_goTypes,
		DependencyIndexes: file_upstream_proto_depIdxs,
		EnumInfos:         file_upstream_proto_enumTypes,
		MessageInfos:      file_upstream_proto_msgTypes,
	}.Build()
	File_upstream_proto = out.File
	file_upstream_proto_rawDesc = nil
	file_upstream_proto_goTypes = nil
	file_upstream_proto_depIdxs = nil
}
